name: password_manager
description: An app to store username and password

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  plugin_player:
    git:
      ref: flutter2
      url: git@github.com:charaku/flutter-media-player.git
  aws_kinesis_api:
    git:
      url: git@github.com:charaku/aws_client.git
      ref: 8c69f12122e9bc46a09ce49e833830f5a5dbc09a
      path: generated/aws_kinesis_api
  agora_rtc_engine: ^4.0.6
  algolia: ^1.0.1
  android_intent: ^2.0.2
  app_settings: ^4.1.1
  audio_session: ^0.1.5
  basic_utils: ^3.3.3
  cached_network_image: ^3.1.0
  camera: ^0.8.1+5
  connectivity: ^3.0.6
  crypto: ^3.0.0
  cupertino_icons: ^1.0.3
  cupertino_will_pop_scope: ^1.1.0
  device_info: ^2.0.2
  dio: ^4.0.0
  dio_http_cache: ^0.3.0
  elastic_client: ^0.3.5
  equatable: ^2.0.3
  event_bus: ^2.0.0
  file_picker: ^3.0.3
  firebase_analytics: ^8.2.0
  firebase_core: ^1.4.0
  firebase_crashlytics: ^2.1.1
  firebase_dynamic_links: ^2.0.7
  firebase_messaging: ^10.0.4
  firebase_remote_config: ^0.10.0+3
  flutter_bloc: ^7.0.1
  flutter_cache_manager: ^3.1.2
  flutter_device_type: ^0.4.0
  flutter_exoplayer: ^0.6.1
  flutter_facebook_auth: ^3.5.0
  flutter_ffmpeg: ^0.4.0
  flutter_local_notifications: ^7.0.0-dev.3
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  flutter_svg_provider: ^0.1.10
  flutter_switch: ^0.3.2
  fluttertoast: ^8.0.7
  get_it: ^7.2.0
  google_sign_in: ^5.0.5
  headset_connection_event: ^2.1.0
  http: ^0.13.0
  http_parser: ^4.0.0
  image_cropper: ^1.4.1
  intl: ^0.17.0
  just_audio: ^0.9.4
  loading_indicator: ^3.0.1
  mime: ^1.0.0
  open_file: ^3.2.1
  package_info: ^2.0.2
  page_view_indicators: ^2.0.0
  palette_generator: ^0.3.0
  path: ^1.8.0
  path_provider: ^2.0.2
  permission_handler: ^8.1.4+2
  phoenix_wings: ^1.0.2
  pin_code_fields: ^7.3.0
  provider: ^5.0.0
  reorderables: ^0.4.1
  share_plus: ^2.1.4
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  sign_in_with_apple: ^3.0.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  timeago: ^3.1.0
  tuple: ^2.0.0
  url_launcher: ^6.0.9
  uuid: ^3.0.4
  video_player: ^2.1.12
  video_thumbnail: ^0.3.3
  volume: ^1.0.1
  volume_controller: ^2.0.2
  wakelock: ^0.5.2
  webview_flutter: ^2.0.10
  wifi_iot: ^0.3.4
  collection: ^1.15.0-nullsafety.4
  async: ^2.6.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
